/*
 * Copyright (c) 2019, Charles Daniels All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <agar/core.h>
#include <agar/gui.h>

#include <stdlib.h>
#include <string.h>

#include "nocsim.h"

/* handy macro to check if a string ends with a certain 4 letter character
 * sequence. This is used for checking file extensions. */
#define check_ext(str, ext) (strlen(str) > 4 && !strcmp(str + strlen(str) - 4, ext))

/* Helper macro for use within event handlers, traverses up the VFS tree to
 * grab the top-level driver object. This is needed since AG_ObjectRoot()
 * dosen't always traverse all the way up the tree in one go */
#define get_dri() (AG_Driver*) AG_ObjectFindParent(AG_SELF(), "agDrivers", NULL)

#define AG_FixedTextboxNew(parent, label, fmt, ...) __extension__ ({ \
	AG_Textbox* __tb = AG_TextboxNewS(parent, AG_TEXTBOX_READONLY | AG_TEXTBOX_HFILL, label); \
	AG_TextboxPrintf(__tb, fmt, __VA_ARGS__); \
	__tb->ed->flags |= AG_EDITABLE_HFILL; \
	AG_EditableSizeHint(__tb->ed, stackPrintf("%s          ", \
		stackPrintf(fmt, __VA_ARGS__))); \
	__tb;})

/* handler for "quit" menu item */
void QuitApplication(AG_Event *event) {
	AG_DestroyGraphics();
	AG_Destroy();
	AG_Quit();
}

/* If the debugger is enabled, the "Launch Debugger" menu item will use this
 * to display the LibAgar debugging window */
#ifdef ENABLE_DEBUGGER
void LaunchDebugger(AG_Event *event) {
	AG_Driver* dri;
	AG_Window* db_window;

	/* Fetch the top-level driver object, which is also the parent of the
	 * main window. We will attach the debugger window to this object. */
	dri = (AG_Driver*) get_dri();

	db_window = AG_GuiDebugger(dri);
	AG_WindowShow(db_window);
}
#endif


/* lets us use AG_TAILQ */
#define _Nullable
AG_GraphEdge* FindEdge(AG_Graph* g, AG_GraphVertex* v1, AG_GraphVertex* v2) {
	AG_GraphEdge* edge;
	AG_TAILQ_HEAD_(ag_graph_edge) edges;
	AG_TAILQ_FOREACH(edge, &g->edges, edges) {
		if (edge->v1 == v1 && edge->v2 == v2) {
			return edge;
		}
	}
}
#undef _Nullable

static void
RenderToSurface(AG_Event *event)
{
    AG_Button *btn = AG_PTR(1);
    AG_Window *winParent = AG_PTR(2), *win;
    AG_Surface *S;

    /* Render the AG_Button to a surface. */
    if ((S = AG_WidgetSurface(btn)) == NULL) {
        AG_TextMsgFromError();
        return;
    }

    /* Display the rendered surface. */
    if ((win = AG_WindowNew(0)) != NULL) {
        AG_WindowSetCaptionS(win, "Rendered surface");
        AG_LabelNew(win, 0, "Surface generated from %s:", AGOBJECT(btn)->name);
        AG_SeparatorNewHoriz(win);
        AG_PixmapFromSurface(win, 0, S);
        AG_SeparatorNewHoriz(win);
        AG_LabelNew(win, 0,
            "Format: %u x %u x %d bpp",
            S->w, S->h,
            S->format.BitsPerPixel);

        AG_WindowAttach(winParent, win);
        AG_WindowShow(win);
    }
}

/* handler for the OK button in the file dialog */
void ExportGraph(AG_Event* event) {

	AG_Graph* g = (AG_Graph*) AG_PTR_NAMED("g");

	/* the path and filetype are generated by the file-chosen event type */
	char* path = AG_STRING(3);
	AG_FileType* ft = (AG_FileType*) AG_PTR(4);

	/* this is not safe, as it does not do bounds checking */
	char* path_with_ext = malloc(sizeof(char) * (strlen(path) + 4));
	strcpy(path_with_ext, path);

	/* force the widget to redraw, to make sure that the state we pull
	 * out of the surface is current */
	AG_WidgetDraw(g);

	/* copy the current state of the g surface to a new surface object */
	AG_Surface* surf = AG_WidgetSurface(g);

	/* this is an awful way to do this... don't do this */
	if (strcmp(ft->descr, "PNG image") == 0) {
		if (!check_ext(path, ".png")) {
			/* unsafe, does not bounds check */
			strcat(path_with_ext, ".png");
		}
		AG_SurfaceExportPNG(surf, path_with_ext, 0);

	} else if (strcmp(ft->descr, "JPEG image") == 0) {
		if (!check_ext(path, ".jpg")) {
			/* unsafe, does not bounds check */
			strcat(path_with_ext, ".jpg");
		}
		AG_SurfaceExportJPEG(surf, path_with_ext, 80, 0);

	} else {
		if (!check_ext(path, ".bmp")) {
			/* unsafe, does not bounds check */
			strcat(path_with_ext, ".bmp");
		}
		AG_SurfaceExportBMP(surf, path, 0);
		/* AG_SurfaceExportBMP(surf, path); */
	}

	/* clean up the surface object */
	AG_SurfaceFree(surf);

}

void HandleVertexSelection(AG_Event* event) {
	AG_GraphVertex* vtx = AG_PTR(1);
	AG_Driver* dri = get_dri();
	AG_Box* inner;
	nocsim_node* node;

	AG_Box* box = AG_GetPointer(dri, "infobox_p");
	AG_Object* parent = AG_ObjectParent(AGOBJECT(box));
	AG_ObjectDelete(box);
	/* box = AG_BoxNew(parent, AG_BOX_HORIZ, AG_BOX_EXPAND); */
	box = AG_BoxNew(parent, AG_BOX_VERT, AG_BOX_EXPAND);
	AG_SetPointer(dri, "infobox_p", box);

	node = ((nocsim_node*) vtx->userPtr);

	if (vtx->userPtr != NULL) {

		inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_FRAME | AG_BOX_HFILL);
		AG_BoxSetLabelS(inner, "node data");

#define prval(label, fmt, ...) AG_FixedTextboxNew(inner, label, fmt, __VA_ARGS__) 

		prval("ID", "%s", node->id);
		prval("type", "%s", NOCSIM_NODE_TYPE_TO_STR(node->type));

		prval("node number"   , "%i" , node->node_number);
		prval("type number"   , "%i" , node->type_number);
		prval("row"           , "%i" , node->row);
		prval("col"           , "%i" , node->col);
		prval("behavior"      , "%s" , node->behavior);
		if (node->type == node_PE) {
			prval("flits pending" , "%u" , node->pending->length);
		} else {
			prval("flits pending" , "%s" , "N/A");
		}

		inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_FRAME | AG_BOX_HFILL);
		AG_BoxSetLabelS(inner, "performance counters");

		prval("injected", "%li", node->injected);
		prval("routed", "%li", node->routed);

#undef prval


	} else {
		AG_LabelNewS(box, 0, "node data inaccessible");
	}

	AG_WidgetHide(box);
	AG_WidgetShow(box);

}

void populate_link_info(AG_Box* box, AG_Driver* dri, nocsim_state* state, nocsim_link* l) {

	if (l == NULL) { return; }

	AG_Box* inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_FRAME | AG_BOX_HFILL);
	AG_BoxSetLabel(inner, "link data");

#define prval(label, fmt, ...) AG_FixedTextboxNew(inner, label, fmt, __VA_ARGS__) 

	/* TODO: when links become queues, this will need to be updated */
	prval("flits", "%u", (l->flit == NULL) ? 0 : 1);

	inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_FRAME | AG_BOX_HFILL);
	AG_BoxSetLabelS(inner, "performance counters");

	prval("load", "%li", l->load);

	/* for bidirectional links, allow us to swap which direction we are
	 * looking at */
	if (nocsim_link_by_nodes(state, l->to->id, l->from->id)) {
		/* TODO: also show link info in the opposite direction */
	}

#undef prval

}


void show_link_info(nocsim_state* state, AG_Driver* dri, nocsim_link* l) {
	AG_Box* box = AG_GetPointer(dri, "infobox_p");
	AG_Object* parent = AG_ObjectParent(AGOBJECT(box));
	AG_ObjectDelete(box);
	box = AG_BoxNew(parent, AG_BOX_VERT, AG_BOX_EXPAND);
	AG_Box* inner;
	AG_SetPointer(dri, "infobox_p", box);

	inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_HFILL| AG_BOX_FRAME);
	AG_BoxSetLabel(inner, "%s -> %s", l->from->id, l->to->id);
	populate_link_info(inner, dri, state, l);

	inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_HFILL| AG_BOX_FRAME);
	AG_BoxSetLabel(inner, "%s -> %s", l->to->id, l->from->id);
	populate_link_info(inner, dri, state, nocsim_link_by_nodes(
		state, l->to->id, l->from->id));

	AG_WidgetHide(box);
	AG_WidgetShow(box);

}



void HandleEdgeSelection(AG_Event* event) {
	AG_GraphEdge* edge = AG_PTR(2);
	nocsim_state* state = AG_PTR_NAMED("state");
	AG_GraphVertex* vtx1 = edge->v1;
	AG_GraphVertex* vtx2 = edge->v2;
	AG_Driver* dri = get_dri();
	nocsim_node* node1;
	nocsim_node* node2;
	nocsim_link* l;

	AG_Box* box = AG_GetPointer(dri, "infobox_p");
	AG_Object* parent = AG_ObjectParent(AGOBJECT(box));
	AG_ObjectDelete(box);
	/* box = AG_BoxNew(parent, AG_BOX_HORIZ, AG_BOX_EXPAND); */
	box = AG_BoxNew(parent, AG_BOX_VERT, AG_BOX_EXPAND);
	AG_SetPointer(dri, "infobox_p", box);
	AG_LabelNewS(box, 0, "edge data inaccessible");

	if (vtx1 == NULL || vtx2 == NULL) { return; }
	node1= (nocsim_node*) vtx1->userPtr;
	node2 = (nocsim_node*) vtx2->userPtr;
	if (node1 == NULL || node2 == NULL) { return; }

	l = nocsim_link_by_nodes(state, node1->id, node2->id);

	if (l == NULL) {
		l = nocsim_link_by_nodes(state, node2->id, node1->id);
	}

	if (l == NULL) { return; }

	show_link_info(state, dri, l);

}

/* Export the graph view to a file */
void ExportGraphDialog(AG_Event* event) {

	AG_Graph* g = (AG_Graph*) AG_PTR_NAMED("g");

	/* create a new window in which to display the file dialog */
	AG_Window* fdwin = AG_WindowNew(0);

	AG_FileDlg* f = AG_FileDlgNew(fdwin,
			AG_FILEDLG_SAVE |  /* make sure the file is writable */
			AG_FILEDLG_EXPAND |
			AG_FILEDLG_CLOSEWIN /* close window when done */
		);

	/* Hook into the user choosing a file. file-chosen will give us
	 * both the path to the chosen file, and also the chosen file type. */
	AG_SetEvent(f, "file-chosen", ExportGraph,
				"%p(g)", g);

	/* Set up valid output types. Note that the file type descriptions are
	 * string-matched to determine which AG_SurfaceExport function to call
	 * in ExportGraph -- they need to be changed in both places. */
	AG_FileDlgAddType(f, "PNG image", ".png", NULL, NULL);
	AG_FileDlgAddType(f, "JPEG image", ".jpg", NULL, NULL);
	AG_FileDlgAddType(f, "BPM image", ".bmp", NULL, NULL);

	/* display the file dialog window */
	AG_WindowShow(fdwin);

}


void graph_update(nocsim_state* state, AG_Driver* dri, AG_Box* box) {
	nocsim_node* cursor;
	nocsim_node* inner;
	unsigned int i;
	unsigned int j;
	AG_GraphVertex* vtx = NULL;
	AG_Graph* g;
	AG_Window* win;
	AG_Box* infobox;

	int* show_node_labels;
	int* show_edge_labels;

	/* delete the existing network view so we have a clean state to work
	 * with */
	g = AG_GetPointer(dri, "graph_p");

	/* this function will populate the info box */
	infobox = AG_GetPointer(dri, "infobox_p");
	AG_AddEvent(g, "graph-vertex-selected", HandleVertexSelection, NULL);
	AG_AddEvent(g, "graph-edge-selected", HandleEdgeSelection, "%p(state)", state);

	show_node_labels = AG_GetPointer(dri, "show_node_labels");
	show_edge_labels = AG_GetPointer(dri, "show_edge_labels");

	vec_foreach(state->nodes, cursor, i) {
		/* Only create a new vertex if one does not exist yet for this
		 * element.
		 *
		 * XXX: this assumes nodes can never be deleted */
		vtx = AG_GraphVertexFind(g, (void*) cursor);
		if (vtx == NULL) {
			vtx = AG_GraphVertexNew(g, (void*) cursor);
		}

		if (*show_node_labels == 1) {
			AG_GraphVertexLabelS(vtx, cursor->id);
		} else {
			AG_GraphVertexLabelS(vtx, "");
		}


		if (cursor->type == node_router) {
			AG_GraphVertexPosition(vtx, cursor->col * 150, cursor->row * 150);
		} else {
			AG_GraphVertexPosition(vtx, cursor->col * 150 + 75, cursor->row * 150 + 75);
		}

	}

	/* TODO: performance could be _much_ improved here */
	vec_foreach(state->nodes, cursor, i) {
		vec_foreach(state->nodes, inner, j) {
			if (i == j) {continue; }

			AG_GraphVertex* vtx1;
			AG_GraphVertex* vtx2;
			AG_GraphEdge* e;
			nocsim_link* l;

			/* check if there is a link between these nodes */
			if (nocsim_link_by_nodes(state, cursor->id, inner->id) == NULL) {
				continue;
			}

			vtx1 = AG_GraphVertexFind(g, cursor);
			vtx2 = AG_GraphVertexFind(g, inner);
			if (vtx1 == NULL || vtx2 == NULL) { continue; }

			e = FindEdge(g, vtx1, vtx2);
			if (e == NULL) {
				e = AG_GraphEdgeNew(g, vtx1, vtx2, NULL);
			}

			l = nocsim_link_by_nodes(state, inner->id, cursor->id);

			/* the link goes both ways */
			if (l != NULL) {
				/* We want to make sure the bidirectional links only
				 * get generated once, so we pick the smaller of the
				 * two pointer values arbitrarily as the "origin" and
				 * ignore it. */
				if ((long int) vtx2 < (long int) vtx1) { continue; }

				e->type = AG_GRAPH_EDGE_UNDIRECTED;
				if (*show_edge_labels == 1) {
					AG_GraphEdgeLabel(e, "%s <-> %s", cursor->id, inner->id);
				} else {
					AG_GraphEdgeLabelS(e, "");
				}
			} else {
				e->type = AG_GRAPH_EDGE_DIRECTED;
				if (*show_edge_labels == 1) {
					AG_GraphEdgeLabel(e, "%s -> %s", cursor->id, inner->id);
				} else {
					AG_GraphEdgeLabelS(e, "");
				}
			}


		}
	}

}

void ToggleEdgeLabels(AG_Event* event) {
	AG_Driver* dri = get_dri();
	nocsim_state* state = AG_PTR(1);
	AG_Box* box = AG_PTR(2);

	int* show_edge_labels;
	show_edge_labels = AG_GetPointer(dri, "show_edge_labels");

	if (*show_edge_labels == 0) {
		*show_edge_labels = 1;
	} else {
		*show_edge_labels = 0;
	}

	graph_update(state, dri, box);

}

void ToggleNodeLabels(AG_Event* event) {
	AG_Driver* dri = get_dri();
	nocsim_state* state = AG_PTR(1);
	AG_Box* box = AG_PTR(2);

	int* show_node_labels;
	show_node_labels = AG_GetPointer(dri, "show_node_labels");

	if (*show_node_labels == 0) {
		*show_node_labels = 1;
	} else {
		*show_node_labels = 0;
	}

	graph_update(state, dri, box);

}

void simulation_update(nocsim_state* state, AG_Driver* dri) {
	AG_Box* box = AG_GetPointer(dri, "siminfo_p");
	AG_Box* inner;
	AG_Object* parent = AG_ObjectParent(AGOBJECT(box));
	AG_ObjectDelete(box);
	box = AG_BoxNew(parent, AG_BOX_VERT, AG_BOX_EXPAND);
	AG_SetPointer(dri, "siminfo_p", box);


	inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_FRAME | AG_BOX_HFILL);
	AG_BoxSetLabelS(inner, "general");

#define prval(label, fmt, ...) AG_FixedTextboxNew(inner, label, fmt, __VA_ARGS__) 

	prval("tick", "%lu", state->tick);
	prval("num_PE", "%u", state->num_PE);
	prval("num_router", "%u", state->num_router);
	prval("num_node", "%u", state->num_node);
	prval("flit_no", "%lu", state->flit_no);
	prval("max_row", "%u", state->max_row);
	prval("max_col", "%u", state->max_col);

	inner = AG_BoxNew(box, AG_BOX_VERT, AG_BOX_FRAME | AG_BOX_HFILL);
	AG_BoxSetLabelS(inner, "instruments");

	for (int i = 1 ; i < ENUMSIZE_INSTRUMENT ; i++) {
		if (state->instruments[i] == NULL) {
			prval(NOCSIM_INSTRUMENT_TO_STR(i), "%s", "(none)");
		} else {
			prval(NOCSIM_INSTRUMENT_TO_STR(i), "%s", state->instruments[i]);
		}
	}


#undef prval

	AG_WidgetHide(box);
	AG_WidgetShow(box);

}


void EnterLine(AG_Event* event) {
	AG_Console* cons = AG_PTR(1);
	AG_Textbox *tb = AG_PTR(2);
	nocsim_state* state = AG_PTR(3);
	AG_Box* box = AG_PTR(4);
	char* s;
	AG_ConsoleLine* line;
	char buf[1024];

	/* void AG_ConsoleMsgEdit (AG_ConsoleLine *line, const char *s) */

	AG_Color red;
	AG_ColorRGB_8(&red, 255, 16, 16);

	AG_Color green;
	AG_ColorRGB_8(&green, 16, 255, 16);

	AG_Color white;
	AG_ColorRGB_8(&white, 255, 255, 255);

	s = AG_TextboxDupString(tb);

	snprintf(buf, sizeof(buf), "%% %s", s);
	line = AG_ConsoleMsgS(cons, buf);

	if (Tcl_Eval(state->interp, s) == TCL_OK) {
		snprintf(buf, sizeof(buf), "(OK   ) %% %s", s);
		AG_ConsoleMsgEdit(line, buf);
		nocsim_console_writelines(cons, Tcl_GetStringResult(state->interp), &white);
	} else {
		snprintf(buf, sizeof(buf), "(ERROR) %% %s\t\t", s);
		AG_ConsoleMsgEdit(line, buf);
		AG_ConsoleMsgColor(line, &red);
		nocsim_console_writelines(cons, Tcl_GetStringResult(state->interp), &red);
	}
	AG_TextboxSetString(tb, "");
	/* AG_Free(s); */

	graph_update(state, get_dri(), box);
	simulation_update(state, get_dri());

}

int main(int argc, char *argv[]) {
	AG_Window *win;
	AG_Graph* g;
	AG_Driver* dri;
	AG_MenuItem* temp;
	AG_Menu* menu;
	AG_Console* cons;
	AG_Button *btn;
	AG_Textbox *tb;
	nocsim_state* state;
	AG_Box* box;
	AG_Pane* outer_pane;
	AG_Pane* inner_pane;
	AG_Pane* infopane;

	int show_node_labels = 1;
	int show_edge_labels = 1;

	/* Initialize LibAgar */
	if (AG_InitCore(NULL, 0) == -1 ||
			AG_InitGraphics(0) == -1)
		return (1);
	win = AG_WindowNew(0);
	AG_WindowSetCaptionS (win, "nocsim-gui");
	AG_WindowSetGeometry(win, -1, -1, 1100, 900);

	/* setup the state handler and edge creation vertex variables */
	dri = (AG_Driver*) AG_ObjectRoot(win);

	menu = AG_MenuNew(win, 0);

	outer_pane = AG_PaneNewVert(win, AG_PANE_EXPAND);
	inner_pane = AG_PaneNewHoriz(outer_pane->div[0], AG_PANE_DIV1FILL | AG_PANE_EXPAND);

	/* instantiate the graph */
	g = AG_GraphNew(inner_pane->div[1], AG_GRAPH_EXPAND);
	AG_GraphSizeHint(g, 800, 600);
	AG_SetPointer(dri, "graph_p", g);

	/* global flags for edge/node labels */
	AG_SetPointer(dri, "show_node_labels", &show_node_labels);
	AG_SetPointer(dri, "show_edge_labels", &show_edge_labels);

	/* instantiate the "File" menu dropdown */
	AG_MenuItem* menu_file = AG_MenuNode(menu->root, "File", NULL);

	/* instantiate the contents of the File menu */
	{
		AG_MenuAction(menu_file, "Export", NULL, ExportGraphDialog,
				"%p(g)", g);

		AG_MenuSeparator(menu_file);

		AG_MenuAction(menu_file, "Quit", NULL, QuitApplication, NULL);

#ifdef ENABLE_DEBUGGER
		AG_MenuSeparator(menu_file);
		AG_MenuAction(menu_file, "Launch Debugger", NULL, LaunchDebugger, NULL);
#endif
	}

	/* setup the console */
	cons = AG_ConsoleNew(outer_pane->div[1], AG_CONSOLE_EXPAND);
	AG_SetStyle(cons, "font-family", "Courier");
	state = nocsim_create_interp(NULL, cons, argc, argv);

	/* instantiate the "View" menu dropdown */
	AG_MenuItem* menu_view = AG_MenuNode(menu->root, "View", NULL);

	{
		AG_MenuAction(menu_view, "Toggle Edge Labels", NULL, ToggleEdgeLabels, "%p,%p", state, inner_pane->div[1]);
		AG_MenuAction(menu_view, "Toggle Node Labels", NULL, ToggleNodeLabels, "%p,%p", state, inner_pane->div[1]);
	}


	/* setup text entry box */
	box = AG_BoxNewHoriz(outer_pane->div[1], AG_BOX_HFILL);
	{
		tb = AG_TextboxNew(box,
		    AG_TEXTBOX_EXCL | AG_TEXTBOX_HFILL | AG_TEXTBOX_VFILL,
		    "Input: ");
		AG_SetEvent(tb, "textbox-return", EnterLine, "%p,%p,%p,%p", cons, tb, state, inner_pane->div[1]);
		AG_WidgetFocus(tb);

		btn = AG_ButtonNewFn(box, 0, "Enter", EnterLine, "%p,%p,%p,%p", cons, tb, state,inner_pane->div[1]);
		AG_WidgetSetFocusable(btn, 0);
	}

	/* display the window */
	AG_WindowShow(win);

	/* split up node info view and simulation info view */
	infopane = AG_PaneNewVert(inner_pane->div[0], AG_PANE_EXPAND);
	AG_PaneMoveDividerPct(infopane, 50);

	/* info view area */
	box = AG_BoxNew(
			AG_ScrollviewNew(infopane->div[0], AG_SCROLLVIEW_BY_MOUSE | AG_SCROLLVIEW_EXPAND),
			AG_BOX_VERT, AG_BOX_EXPAND);
	AG_SetPointer(dri, "infobox_p", box);

	/* this function will populate the info box */
	AG_AddEvent(g, "graph-vertex-selected", HandleVertexSelection, NULL);
	AG_AddEvent(g, "graph-edge-selected", HandleEdgeSelection, "%p(state)", state);

	/* simulation info view */
	box = AG_BoxNew(
			AG_ScrollviewNew(infopane->div[1], AG_SCROLLVIEW_BY_MOUSE | AG_SCROLLVIEW_EXPAND),
			AG_BOX_VERT, AG_BOX_EXPAND);
	AG_SetPointer(dri, "siminfo_p", box);
	simulation_update(state, dri);


	AG_EventLoop();
	return (0);
}

#undef AG_FixedTextboxNew
