/* Simple demonstration application -- implements a small graph editor using
 * LibAgar's graph widget. */

/*
 * Copyright (c) 2019, Charles Daniels All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <agar/core.h>
#include <agar/gui.h>

#include <stdlib.h>
#include <string.h>

#include "nocsim.h"


/* handy macro to check if a string ends with a certain 4 letter character
 * sequence. This is used for checking file extensions. */
#define check_ext(str, ext) (strlen(str) > 4 && !strcmp(str + strlen(str) - 4, ext))

/* Helper macro for use within event handlers, traverses up the VFS tree to
 * grab the top-level driver object. This is needed since AG_ObjectRoot()
 * dosen't always traverse all the way up the tree in one go */
#define get_dri() (AG_Driver*) AG_ObjectFindParent(AG_SELF(), "agDrivers", NULL)

/* handler for "quit" menu item */
void QuitApplication(AG_Event *event) {
	AG_DestroyGraphics();
	AG_Destroy();
	AG_Quit();
}

/* If the debugger is enabled, the "Launch Debugger" menu item will use this
 * to display the LibAgar debugging window */
#ifdef ENABLE_DEBUGGER
void LaunchDebugger(AG_Event *event) {
	AG_Driver* dri;
	AG_Window* db_window;

	/* Fetch the top-level driver object, which is also the parent of the
	 * main window. We will attach the debugger window to this object. */
	dri = (AG_Driver*) get_dri();

	db_window = AG_GuiDebugger(dri);
	AG_WindowShow(db_window);
}
#endif

static void
RenderToSurface(AG_Event *event)
{
    AG_Button *btn = AG_PTR(1);
    AG_Window *winParent = AG_PTR(2), *win;
    AG_Surface *S;

    /* Render the AG_Button to a surface. */
    if ((S = AG_WidgetSurface(btn)) == NULL) {
        AG_TextMsgFromError();
        return;
    }

    /* Display the rendered surface. */
    if ((win = AG_WindowNew(0)) != NULL) {
        AG_WindowSetCaptionS(win, "Rendered surface");
        AG_LabelNew(win, 0, "Surface generated from %s:", AGOBJECT(btn)->name);
        AG_SeparatorNewHoriz(win);
        AG_PixmapFromSurface(win, 0, S);
        AG_SeparatorNewHoriz(win);
        AG_LabelNew(win, 0,
            "Format: %u x %u x %d bpp",
            S->w, S->h,
            S->format.BitsPerPixel);

        AG_WindowAttach(winParent, win);
        AG_WindowShow(win);
    }
}

/* handler for the OK button in the file dialog */
void ExportGraph(AG_Event* event) {

	AG_Graph* g = (AG_Graph*) AG_PTR_NAMED("g");
	AG_Label* statuslabel = (AG_Label*) AG_PTR_NAMED("statuslabel");

	/* the path and filetype are generated by the file-chosen event type */
	char* path = AG_STRING(3);
	AG_FileType* ft = (AG_FileType*) AG_PTR(4);

	/* this is not safe, as it does not do bounds checking */
	char* path_with_ext = malloc(sizeof(char) * (strlen(path) + 4));
	strcpy(path_with_ext, path);

	/* force the widget to redraw, to make sure that the state we pull
	 * out of the surface is current */
	AG_WidgetDraw(g);

	/* copy the current state of the g surface to a new surface object */
	AG_Surface* surf = AG_WidgetSurface(g);

	/* this is an awful way to do this... don't do this */
	if (strcmp(ft->descr, "PNG image") == 0) {
		if (!check_ext(path, ".png")) {
			/* unsafe, does not bounds check */
			strcat(path_with_ext, ".png");
		}
		AG_SurfaceExportPNG(surf, path_with_ext, 0);

	} else if (strcmp(ft->descr, "JPEG image") == 0) {
		if (!check_ext(path, ".jpg")) {
			/* unsafe, does not bounds check */
			strcat(path_with_ext, ".jpg");
		}
		AG_SurfaceExportJPEG(surf, path_with_ext, 80, 0);

	} else {
		if (!check_ext(path, ".bmp")) {
			/* unsafe, does not bounds check */
			strcat(path_with_ext, ".bmp");
		}
		AG_SurfaceExportBMP(surf, path, 0);
		/* AG_SurfaceExportBMP(surf, path); */
	}

	/* clean up the surface object */
	AG_SurfaceFree(surf);

}

/* Export the graph view to a file */
void ExportGraphDialog(AG_Event* event) {

	AG_Graph* g = (AG_Graph*) AG_PTR_NAMED("g");
	AG_Label* statuslabel = (AG_Label*) AG_PTR_NAMED("statuslabel");

	/* create a new window in which to display the file dialog */
	AG_Window* fdwin = AG_WindowNew(0);

	AG_FileDlg* f = AG_FileDlgNew(fdwin,
			AG_FILEDLG_SAVE |  /* make sure the file is writable */
			AG_FILEDLG_EXPAND |
			AG_FILEDLG_CLOSEWIN /* close window when done */
		);

	/* Hook into the user choosing a file. file-chosen will give us
	 * both the path to the chosen file, and also the chosen file type. */
	AG_SetEvent(f, "file-chosen", ExportGraph,
				"%p(g),%p(statuslabel)", g, statuslabel);

	/* Set up valid output types. Note that the file type descriptions are
	 * string-matched to determine which AG_SurfaceExport function to call
	 * in ExportGraph -- they need to be changed in both places. */
	AG_FileDlgAddType(f, "PNG image", ".png", NULL, NULL);
	AG_FileDlgAddType(f, "JPEG image", ".jpg", NULL, NULL);
	AG_FileDlgAddType(f, "BPM image", ".bmp", NULL, NULL);

	/* display the file dialog window */
	AG_WindowShow(fdwin);

}

void graph_update(nocsim_state* state, AG_Driver* dri, AG_Box* box) {
	nocsim_node* cursor;
	nocsim_node* inner;
	unsigned int i;
	unsigned int j;
	AG_GraphVertex* vtx = NULL;
	AG_Graph* g;
	AG_Window* win;

	/* delete the existing network view so we have a clean state to work
	 * with */
	g = AG_GetPointer(dri, "graph_p");
	AG_ObjectDelete(g);
	g = AG_GraphNew(box, AG_GRAPH_EXPAND);
	AG_GraphSizeHint(g, 800, 600);
	AG_SetPointer(dri, "graph_p", g);

	/* force the newly created widget to draw */
	AG_WidgetHide(g);
	AG_WidgetShow(g);

	vec_foreach(state->nodes, cursor, i) {
		vtx = AG_GraphVertexNew(g, (void*) cursor);
		AG_GraphVertexLabelS(vtx, cursor->id);
		AG_GraphVertexPosition(vtx, cursor->col * 100, cursor->row * 100);
	}

	/* TODO: performance could be _much_ improved here */
	vec_foreach(state->nodes, cursor, i) {
		vec_foreach(state->nodes, inner, j) {
			if (i == j) {continue; }

			AG_GraphVertex* vtx1;
			AG_GraphVertex* vtx2;

			/* check if there is a link between these nodes */
			if (nocsim_link_by_nodes(state, cursor->id, inner->id) == NULL) {
				continue;
			}

			vtx1 = AG_GraphVertexFind(g, cursor);
			vtx2 = AG_GraphVertexFind(g, inner);
			if (vtx1 == NULL || vtx2 == NULL) { continue; }

			AG_GraphEdgeNew(g, vtx1, vtx2, NULL);

		}
	}

}


void EnterLine(AG_Event* event) {
	AG_Console* cons = AG_PTR(1);
	AG_Textbox *tb = AG_PTR(2);
	nocsim_state* state = AG_PTR(3);
	AG_Box* box = AG_PTR(4);
	char* s;

	s = AG_TextboxDupString(tb);

	Tcl_Eval(state->interp, s);
	AG_ConsoleMsgS(cons, Tcl_GetStringResult(state->interp));
	AG_TextboxSetString(tb, "");
	/* AG_Free(s); */

	graph_update(state, get_dri(), box);

}

int main(int argc, char *argv[]) {
	AG_Window *win;
	AG_Graph* g;
	AG_Statusbar* statusbar;
	AG_Label* statuslabel;
	AG_Driver* dri;
	AG_MenuItem* temp;
	AG_Menu* menu;
	AG_Console* cons;
	AG_Button *btn;
	AG_Textbox *tb;
	nocsim_state* state;
	AG_Box* box;
	AG_Pane* pane;

	state = nocsim_create_interp(NULL, argc, argv);

	/* Initialize LibAgar */
	if (AG_InitCore(NULL, 0) == -1 ||
			AG_InitGraphics(0) == -1)
		return (1);
	win = AG_WindowNew(0);

	/* set the window title */
	AG_WindowSetCaptionS (win, "nocsim-gui");

	AG_WindowSetGeometry(win, -1, -1, 800, 1000);

	/* setup the state handler and edge creation vertex variables */
	dri = (AG_Driver*) AG_ObjectRoot(win);

	menu = AG_MenuNew(win, 0);

	pane = AG_PaneNewVert(win, AG_PANE_EXPAND);

	/* instantiate the graph */
	g = AG_GraphNew(pane->div[0], AG_GRAPH_EXPAND);
	AG_GraphSizeHint(g, 800, 600);
	AG_SetPointer(dri, "graph_p", g);

	/* Setup the status bar at the bottom of the window */
	AG_SeparatorNew(win, AG_SEPARATOR_HORIZ);
	statusbar = AG_StatusbarNew(win, AG_STATUSBAR_HFILL);
	statuslabel = AG_StatusbarAddLabel(statusbar, "");
	AG_LabelText(statuslabel, "ready");

	/* instantiate the "File" menu dropdown */
	AG_MenuItem* menu_file = AG_MenuNode(menu->root, "File", NULL);

	/* instantiate the contents of the File menu */
	{
		AG_MenuAction(menu_file, "Export", NULL, ExportGraphDialog,
				"%p(g),%p(statuslabel)", g, statuslabel);

		AG_MenuSeparator(menu_file);

		AG_MenuAction(menu_file, "Quit", NULL, QuitApplication, NULL);

#ifdef ENABLE_DEBUGGER
		AG_MenuSeparator(menu_file);
		AG_MenuAction(menu_file, "Launch Debugger", NULL, LaunchDebugger, NULL);
#endif
	}

	cons = AG_ConsoleNew(pane->div[1], AG_CONSOLE_EXPAND);
	/* AG_SetStyle(cons, "font-family", "Courier"); */
	box = AG_BoxNewHoriz(pane->div[1], AG_BOX_HFILL);
	/* AG_SetStyle(box, "font-size", "100%"); */
	{
		tb = AG_TextboxNew(box,
		    AG_TEXTBOX_EXCL | AG_TEXTBOX_HFILL | AG_TEXTBOX_VFILL,
		    "Input: ");
		AG_SetEvent(tb, "textbox-return", EnterLine, "%p,%p,%p,%p", cons, tb, state, pane->div[0]);
		AG_WidgetFocus(tb);

		btn = AG_ButtonNewFn(box, 0, "Enter", EnterLine, "%p,%p,%p,%p", cons, tb, state, pane->div[0]);
		AG_WidgetSetFocusable(btn, 0);
	}

	/* display the window */
	AG_WindowShow(win);

	AG_EventLoop();
	return (0);
}
