version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile

jobs:
  compile:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: pwd
      - run ls -lah
      - run: ./scripts.ci.sh
