version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile

jobs:
  compile:
    parallelism: 1
    docker:
      - image: charlesdaniels/ikos_ubuntu:v2.1
    steps:
      - checkout
      - run: ./scripts/ci.sh
