#ifndef NOC_TOOLS_CONSTANTS
#define NOC_TOOLS_CONSTANTS

#define NOC_TOOLS_VERSION_MAJOR "2"
#define NOC_TOOLS_VERSION_MINOR "0"
#define NOC_TOOLS_VERSION_PATCH "0"
#define NOC_TOOLS_VERSION_SUFFIX "dev"
#define NOC_TOOLS_VERSION ""NOC_TOOLS_VERSION_MAJOR"."NOC_TOOLS_VERSION_MINOR"."NOC_TOOLS_VERSION_PATCH

#endif
